package com.iss_mr_grp7_job_recommender.iss_mr_grp7_job_recommender;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Applicant Info")
public class Applicant implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Field of Study")
	private java.lang.String field;
	@org.kie.api.definition.type.Label("Error and Cause")
	private com.iss_mr_grp7_job_recommender.iss_mr_grp7_job_recommender.ValidationErrorDO error;
	@org.kie.api.definition.type.Label("Highest Education Attained")
	private java.lang.String highestEducation;

	@org.kie.api.definition.type.Label("Total Work Experience")
	private java.lang.Integer workExp;

	@org.kie.api.definition.type.Label("Zip Code")
	private java.lang.Integer zipCode;

	@org.kie.api.definition.type.Label("Preferred Job Scope")
	private java.lang.String prefScope;
	@org.kie.api.definition.type.Label("Job Posting Collection")
	private com.iss_mr_grp7_job_recommender.iss_mr_grp7_job_recommender.JobListCollection jobListCollection;
	@org.kie.api.definition.type.Label("Expected Salary")
	private java.lang.Integer expectedSalary;

	@org.kie.api.definition.type.Label("Preferred Type of Employment")
	private java.lang.String employmentTypePref;

	@org.kie.api.definition.type.Label("Your Technical Skills")
	private java.lang.String technicalSkills;

	@org.kie.api.definition.type.Label(value = "Preferred Job Seniority Level")
	private java.lang.String seniorityLevelPref;

	public Applicant() {
	}

	public java.lang.String getField() {
		return this.field;
	}

	public void setField(java.lang.String field) {
		this.field = field;
	}

	public com.iss_mr_grp7_job_recommender.iss_mr_grp7_job_recommender.ValidationErrorDO getError() {
		return this.error;
	}

	public void setError(
			com.iss_mr_grp7_job_recommender.iss_mr_grp7_job_recommender.ValidationErrorDO error) {
		this.error = error;
	}

	public java.lang.String getHighestEducation() {
		return this.highestEducation;
	}

	public void setHighestEducation(java.lang.String highestEducation) {
		this.highestEducation = highestEducation;
	}

	public java.lang.Integer getWorkExp() {
		return this.workExp;
	}

	public void setWorkExp(java.lang.Integer workExp) {
		this.workExp = workExp;
	}

	public java.lang.Integer getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(java.lang.Integer zipCode) {
		this.zipCode = zipCode;
	}

	public java.lang.String getPrefScope() {
		return this.prefScope;
	}

	public void setPrefScope(java.lang.String prefScope) {
		this.prefScope = prefScope;
	}

	public com.iss_mr_grp7_job_recommender.iss_mr_grp7_job_recommender.JobListCollection getJobListCollection() {
		return this.jobListCollection;
	}

	public void setJobListCollection(
			com.iss_mr_grp7_job_recommender.iss_mr_grp7_job_recommender.JobListCollection jobListCollection) {
		this.jobListCollection = jobListCollection;
	}

	public void populateJobListCollection() {
		jobListCollection = new JobListCollection();

		jobListCollection.populateJobPostings();
	}

	public java.lang.Integer getExpectedSalary() {
		return this.expectedSalary;
	}

	public void setExpectedSalary(java.lang.Integer expectedSalary) {
		this.expectedSalary = expectedSalary;
	}

	public java.lang.String getEmploymentTypePref() {
		return this.employmentTypePref;
	}

	public void setEmploymentTypePref(java.lang.String employmentTypePref) {
		this.employmentTypePref = employmentTypePref;
	}

	public java.lang.String getTechnicalSkills() {
		return this.technicalSkills;
	}

	public void setTechnicalSkills(java.lang.String technicalSkills) {
		this.technicalSkills = technicalSkills;
	}

	public java.lang.String getSeniorityLevelPref() {
		return this.seniorityLevelPref;
	}

	public void setSeniorityLevelPref(java.lang.String seniorityLevelPref) {
		this.seniorityLevelPref = seniorityLevelPref;
	}

	public Applicant(
			java.lang.String field,
			com.iss_mr_grp7_job_recommender.iss_mr_grp7_job_recommender.ValidationErrorDO error,
			java.lang.String highestEducation,
			java.lang.Integer workExp,
			java.lang.Integer zipCode,
			java.lang.String prefScope,
			com.iss_mr_grp7_job_recommender.iss_mr_grp7_job_recommender.JobListCollection jobListCollection,
			java.lang.Integer expectedSalary,
			java.lang.String employmentTypePref,
			java.lang.String technicalSkills,
			java.lang.String seniorityLevelPref) {
		this.field = field;
		this.error = error;
		this.highestEducation = highestEducation;
		this.workExp = workExp;
		this.zipCode = zipCode;
		this.prefScope = prefScope;
		this.jobListCollection = jobListCollection;
		this.expectedSalary = expectedSalary;
		this.employmentTypePref = employmentTypePref;
		this.technicalSkills = technicalSkills;
		this.seniorityLevelPref = seniorityLevelPref;
	}

}