package com.iss_mr_grp7_job_recommender.iss_mr_grp7_job_recommender;

/**
 * This class was automatically generated by the data modeler tool.
 */

import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLConnection;

public class internetCheck implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Internet Connectivity Status")
	private java.lang.Boolean internetStatus;
	public internetCheck() {
	}

	public java.lang.Boolean getInternetStatus() {
		return this.internetStatus;
	}

	public void setInternetStatus(java.lang.Boolean internetStatus) {
		this.internetStatus = internetStatus;
	}

	public void checkInternetConnection() {
		try {
			URL url = new URL("http://www.google.com");
			URLConnection connection = url.openConnection();
			connection.connect();
			connection.getInputStream().close();
			
			System.out.println("Internet Connection Successful.");
			this.setInternetStatus(true);

		}
		
		catch (MalformedURLException e) {
            System.out.println("Internet Not Connected. System operating in offline mode");
     		this.setInternetStatus(false);
        } 

		catch (IOException e) {
			System.out.println("Internet Not Connected. System operating in offline mode");
			this.setInternetStatus(false);
		}

	}

	public internetCheck(java.lang.Boolean internetStatus) {
		this.internetStatus = internetStatus;
	}

}