package com.iss_mr_grp7_job_recommender.iss_mr_grp7_job_recommender;

import java.util.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path; 
import java.nio.file.Paths; 
import java.io.BufferedReader;
import java.io.IOException;
import java.net.URL;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class JobListCollection implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Job List")
	private java.util.List<com.iss_mr_grp7_job_recommender.iss_mr_grp7_job_recommender.JobPosting> jobList;

	public JobListCollection() {
	    jobList = new ArrayList<com.iss_mr_grp7_job_recommender.iss_mr_grp7_job_recommender.JobPosting>();
	}

	public java.util.List<com.iss_mr_grp7_job_recommender.iss_mr_grp7_job_recommender.JobPosting> getJobList() {
		return this.jobList;
	}

	public void setJobList(
			java.util.List<com.iss_mr_grp7_job_recommender.iss_mr_grp7_job_recommender.JobPosting> jobList) {
		this.jobList = jobList;
	}

	public JobListCollection(
			java.util.List<com.iss_mr_grp7_job_recommender.iss_mr_grp7_job_recommender.JobPosting> jobList) {
		this.jobList = jobList;
	}
	
	
	//Add created JobPosting object to list
	public void addJobPosting(JobPosting job){
	   
	    this.jobList.add(job);
	}
	
	
	public void populateJobPostings(String[] attributes){
 	 	
  	    JobPosting job= createJob(attributes); 
  		getJobList().add(job);
        
	}

    private static JobPosting createJob(String[] metadata) 	{
		//Make sure the variables correspond to the correct metadata columns!!
		
		//Assigning info from csv to placeholder variables
		String jobID = metadata[0];
		String employmentType = metadata[1];
		String jobTitle = metadata[2];
		String companyName = metadata[3];
		int workExperienceReq = Integer.parseInt(metadata[5]); 
		String seniorityLevel = metadata[6];
		String jobCategory = metadata[7]; 
		String jobRequirements = metadata[8];
		int minSalary = (int) Double.parseDouble(metadata[9]);
		int maxSalary = (int) Double.parseDouble(metadata[10]); 
	    String salaryRange = metadata[12];
	    String jobQualifications = metadata[13];
	    String jobTechnicalSkills = metadata[14];

		 
		//Build JobPosting object and assign variables to attributes
		JobPosting job = new JobPosting();
		job.setJobID(jobID);
		job.setEmploymentType(employmentType);
		job.setJobTitle(jobTitle);
		job.setCompanyName(companyName);
		job.setWorkExperienceReq(workExperienceReq);
		job.setSeniorityLevel(seniorityLevel);
		job.setJobCategory(jobCategory);
		job.setJobRequirements(jobRequirements);
		job.setMinSalary(minSalary);
		job.setMaxSalary(maxSalary);
		job.setSalaryRange(salaryRange);
		job.setJobQualifications(jobQualifications);
		job.setJobTechnicalSkills(jobTechnicalSkills);
		
		return job;
			 
	}
	

}