package com.iss_mr_grp7_job_recommender.iss_mr_grp7_job_recommender;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Job Posting")
public class JobPosting implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Company Name")
	private java.lang.String companyName;

	@org.kie.api.definition.type.Label("Job Title")
	private java.lang.String jobTitle;

	@org.kie.api.definition.type.Label("Company Location")
	private java.lang.String companyLocation;

	@org.kie.api.definition.type.Label("Job Requirements")
	private java.lang.String jobRequirements;

	@org.kie.api.definition.type.Label("Employment Type")
	private java.lang.String employmentType;

	@org.kie.api.definition.type.Label("Minimum Salary")
	private java.lang.Integer minSalary;

	@org.kie.api.definition.type.Label("Maximum Salary")
	private java.lang.Integer maxSalary;

	@org.kie.api.definition.type.Label("Seniority Level")
	private java.lang.String seniorityLevel;

	@org.kie.api.definition.type.Label("Job Category")
	private java.lang.String jobCategory;

	@org.kie.api.definition.type.Label("Years of Work Experience Required")
	private java.lang.Integer workExperienceReq;

	@org.kie.api.definition.type.Label(value = "Salary Range")
	private java.lang.String salaryRange;

	public JobPosting() {
	}

	public java.lang.String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(java.lang.String companyName) {
		this.companyName = companyName;
	}

	public java.lang.String getJobTitle() {
		return this.jobTitle;
	}

	public void setJobTitle(java.lang.String jobTitle) {
		this.jobTitle = jobTitle;
	}

	public java.lang.String getCompanyLocation() {
		return this.companyLocation;
	}

	public void setCompanyLocation(java.lang.String companyLocation) {
		this.companyLocation = companyLocation;
	}

	public java.lang.String getJobRequirements() {
		return this.jobRequirements;
	}

	public void setJobRequirements(java.lang.String jobRequirements) {
		this.jobRequirements = jobRequirements;
	}

	public java.lang.String getEmploymentType() {
		return this.employmentType;
	}

	public void setEmploymentType(java.lang.String employmentType) {
		this.employmentType = employmentType;
	}

	public java.lang.Integer getMinSalary() {
		return this.minSalary;
	}

	public void setMinSalary(java.lang.Integer minSalary) {
		this.minSalary = minSalary;
	}

	public java.lang.Integer getMaxSalary() {
		return this.maxSalary;
	}

	public void setMaxSalary(java.lang.Integer maxSalary) {
		this.maxSalary = maxSalary;
	}

	public java.lang.String getSeniorityLevel() {
		return this.seniorityLevel;
	}

	public void setSeniorityLevel(java.lang.String seniorityLevel) {
		this.seniorityLevel = seniorityLevel;
	}

	public java.lang.String getJobCategory() {
		return this.jobCategory;
	}

	public void setJobCategory(java.lang.String jobCategory) {
		this.jobCategory = jobCategory;
	}

	public java.lang.Integer getWorkExperienceReq() {
		return this.workExperienceReq;
	}

	public void setWorkExperienceReq(java.lang.Integer workExperienceReq) {
		this.workExperienceReq = workExperienceReq;
	}

	public java.lang.String getSalaryRange() {
		return this.salaryRange;
	}

	public void setSalaryRange(java.lang.String salaryRange) {
		this.salaryRange = salaryRange;
	}

	public JobPosting(java.lang.String companyName, java.lang.String jobTitle,
			java.lang.String companyLocation, java.lang.String jobRequirements,
			java.lang.String employmentType, java.lang.Integer minSalary,
			java.lang.Integer maxSalary, java.lang.String seniorityLevel,
			java.lang.String jobCategory, java.lang.Integer workExperienceReq,
			java.lang.String salaryRange) {
		this.companyName = companyName;
		this.jobTitle = jobTitle;
		this.companyLocation = companyLocation;
		this.jobRequirements = jobRequirements;
		this.employmentType = employmentType;
		this.minSalary = minSalary;
		this.maxSalary = maxSalary;
		this.seniorityLevel = seniorityLevel;
		this.jobCategory = jobCategory;
		this.workExperienceReq = workExperienceReq;
		this.salaryRange = salaryRange;
	}

}