package com.iss_mr_grp7_job_recommender.iss_mr_grp7_job_recommender;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Applicant Info")
public class Applicant implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Highest Education Attained")
	private java.lang.String highest_education;
	@org.kie.api.definition.type.Label("Field of Study")
	private java.lang.String field;
	@org.kie.api.definition.type.Label("Total Work Experience")
	private java.lang.Integer work_exp;
	@org.kie.api.definition.type.Label("Zip Code")
	private java.lang.Integer zip_code;
	@org.kie.api.definition.type.Label("Preferred Job Scope")
	private java.lang.String pref_scope;
	public Applicant() {
	}

	public java.lang.String getHighest_education() {
		return this.highest_education;
	}

	public void setHighest_education(java.lang.String highest_education) {
		this.highest_education = highest_education;
	}

	public java.lang.String getField() {
		return this.field;
	}

	public void setField(java.lang.String field) {
		this.field = field;
	}

	public java.lang.Integer getWork_exp() {
		return this.work_exp;
	}

	public void setWork_exp(java.lang.Integer work_exp) {
		this.work_exp = work_exp;
	}

	public java.lang.Integer getZip_code() {
		return this.zip_code;
	}

	public void setZip_code(java.lang.Integer zip_code) {
		this.zip_code = zip_code;
	}

	public java.lang.String getPref_scope() {
		return this.pref_scope;
	}

	public void setPref_scope(java.lang.String pref_scope) {
		this.pref_scope = pref_scope;
	}

	public Applicant(java.lang.String highest_education,
			java.lang.String field, java.lang.Integer work_exp,
			java.lang.Integer zip_code, java.lang.String pref_scope) {
		this.highest_education = highest_education;
		this.field = field;
		this.work_exp = work_exp;
		this.zip_code = zip_code;
		this.pref_scope = pref_scope;
	}

}