package com.iss_mr_grp7_job_recommender.iss_mr_grp7_job_recommender;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Applicant Info")
public class Applicant implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Field of Study")
	private java.lang.String field;
	@org.kie.api.definition.type.Label("Error and Cause")
	private com.iss_mr_grp7_job_recommender.iss_mr_grp7_job_recommender.ValidationErrorDO error;
	@org.kie.api.definition.type.Label(value = "Highest Education Attained")
	private java.lang.String highestEducation;

	@org.kie.api.definition.type.Label(value = "Total Work Experience")
	private java.lang.Integer workExp;

	@org.kie.api.definition.type.Label(value = "Zip Code")
	private java.lang.Integer zipCode;

	@org.kie.api.definition.type.Label(value = "Preferred Job Scope")
	private java.lang.String prefScope;
	public Applicant() {
	}

	public java.lang.String getField() {
		return this.field;
	}

	public void setField(java.lang.String field) {
		this.field = field;
	}

	public com.iss_mr_grp7_job_recommender.iss_mr_grp7_job_recommender.ValidationErrorDO getError() {
		return this.error;
	}

	public void setError(
			com.iss_mr_grp7_job_recommender.iss_mr_grp7_job_recommender.ValidationErrorDO error) {
		this.error = error;
	}

	public java.lang.String getHighestEducation() {
		return this.highestEducation;
	}

	public void setHighestEducation(java.lang.String highestEducation) {
		this.highestEducation = highestEducation;
	}

	public java.lang.Integer getWorkExp() {
		return this.workExp;
	}

	public void setWorkExp(java.lang.Integer workExp) {
		this.workExp = workExp;
	}

	public java.lang.Integer getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(java.lang.Integer zipCode) {
		this.zipCode = zipCode;
	}

	public java.lang.String getPrefScope() {
		return this.prefScope;
	}

	public void setPrefScope(java.lang.String prefScope) {
		this.prefScope = prefScope;
	}

	public Applicant(
			java.lang.String field,
			com.iss_mr_grp7_job_recommender.iss_mr_grp7_job_recommender.ValidationErrorDO error,
			java.lang.String highestEducation, java.lang.Integer workExp,
			java.lang.Integer zipCode, java.lang.String prefScope) {
		this.field = field;
		this.error = error;
		this.highestEducation = highestEducation;
		this.workExp = workExp;
		this.zipCode = zipCode;
		this.prefScope = prefScope;
	}

}