package com.iss_mr_grp7_job_recommender.iss_mr_grp7_job_recommender;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Applicant2 implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Applicant2() {
    }




}